[settings]
name = "Psyonix Rookie"
loadout_file = "./psyonix.loadout.toml"
psyonix_skill = 1

[details]
developer = "Psyonix"
description = "This is the normal Rookie bot you can play against in Rocket League already"
fun_fact = "Rocket League's bots are implemented with a single behavior tree."
github = ""
language = "Unreal Behavior Trees"